[package]
name = "l337-postgres"
version = "0.2.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>"]
edition = "2018"

[dependencies]
l337 = { path = ".." }
futures = "0.3"
tokio = { version = "0.2", features = ["sync"] }
tokio-postgres = "0.5.0-alpha.2"
log = "0.4.8"
async-trait = "0.1.19"
